---
- ansible.builtin.import_role:
    name: openstack.kolla.etc_hosts

- ansible.builtin.import_tasks: pre-install.yml

- ansible.builtin.import_tasks: install.yml

- ansible.builtin.import_tasks: post-install.yml

- name: Configure ceph for zun
  ansible.builtin.include_tasks: configure-ceph-for-zun.yml
  when:
    - zun_configure_for_cinder_ceph | bool
    - "'zun-compute' in group_names"
