---
- name: Ensure unprivileged users can use ping
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ping_group_range
    value: '0 2147483647'
    state: present
    sysctl_file: "{{ kolla_sysctl_conf_path }}"
  when: ansible_facts.os_family == 'RedHat'
